<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Load extends Model
{
    protected $table = 'example_loads';

    protected $fillable = [
			  'customer_name',
			  'customer_address',
			  'customer_city',
			  'customer_state',
			  'customer_zip',
			  'customer_contact',
			  'customer_email',
			  'customer_phone',
			  'customer_fax',
			  'pick_company',
			  'pick_address',
			  'pick_city',
			  'pick_state', 
			  'pick_zip',
			  'pick_contact',
			  'pick_phone',
			  'pick_email',
			  'delivery_company',
			  'delivery_address',
			  'delivery_city',
			  'delivery_state',
			  'delivery_zip',
			  'delivery_contact',
			  'delivery_phone',
			  'delivery_email',
			  'po_number',
			  'ref_number',
			  'bol_number',
			  'amount_due',
			  'creation_date',
			  'commodity',
			  'special_ins',
			  'internal_notes',
			  'add_stops',
			  'invoice_notes',
			  'update_customer_message'

			  ];
  //    'customer_name',
  // 'customer_address',
  // 'customer_city',
  // 'customer_state',
  // 'customer_zip',
  // 'customer_contact',
  // 'customer_email',
  // 'customer_phone',
  // 'customer_fax',
  // 'carrier_name',
  // 'carrier_address',
  // 'carrier_city',
  // 'carrier_state',
  // 'carrier_zip',
  // 'carrier_contact',
  // 'carrier_email',
  // 'carrier_phone',
  // 'carrier_fax',
  // 'carrier_driver_name',
  // 'carrier_driver_cell',
  // 'pick_company',
  // 'pick_address',
  // 'pick_city',
  // 'pick_state', 
  // 'pick_zip',
  // 'pick_contact',
  // 'pick_phone',
  // 'pick_email',
  // 'pick_date',
  // 'pick_time',
  // 'pick_status',
  // 'delivery_company',
  // 'delivery_address',
  // 'delivery_city',
  // 'delivery_state',
  // 'delivery_zip',
  // 'delivery_contact',
  // 'delivery_phone',
  // 'delivery_email',
  // 'delivery_date',
  // 'delivery_time',
  // 'delivery_status',
  // 'po_number',
  // 'ref_number',
  // 'bol_number',
  // 'expected_pick_date',
  // 'expected_pick_time',
  // 'expected_delivery_date',
  // 'expected_delivery_time',
  // 'created_by',
  // 'its_group',
  // 'amount_due',
  // 'carrier_rate',
  // 'creation_date',
  // 'billed_date',
  // 'approved_carrier_invoice',
  // 'commodity',
  // 'special_ins',
  // 'trailer_type',
  // 'internal_notes',
  // 'add_stops',
  // 'invoice_notes',
  // 'update_customer_message',
  // 'rate_con_creation_date',
  // 'total_miles',
  // 'quick_status_notes',
  // 'vendor_invoice_number',
  // 'vendor_invoice_date',
  // 'remit_name',
  // 'remit_address',
  // 'remit_city',
  // 'remit_state',
  // 'remit_zip'
    


    
}
